### ISSUE TITLE
DB_SYNC

### ISSUE THREAD

**Issue by pastorpflores** [WattRex/Battery-Cycler-Controller#10]

**Comment by mariuscrsn** [comment]
Tests:
- [ ] Populate master DB and extract sql script. @javibu13 will automate it.
- [ ] Add measures to cache via ORM - pytest
- [ ] Push measures to master and check if it works.  - mid_sync
- [ ] Add repetead measures to master. It must fail. - mid_sync
- [ ] Remove measure from cache. - pytest
- [ ] Select again measures to check that it has been removed from cache and no push measures when there is not measures. - mid_sync
