### ISSUE TITLE
Develop a docker platform for production @javibu13

### ISSUE THREAD

**Issue by mariuscrsn** [WattRex/Battery-Cycler-Controller#14]

**Comment by mariuscrsn** [comment]
- [x] deploy script. It must deploy docker platform. It can receive 3 types of arguments:
>- [x] `./deploy.sh` -> deploy cache db and synchronizer container
>- [x] `./deploy.sh sniffer can|scpi` -> check if can or scpi sniffer are available. If not, restart it.
>- [x]  `./deploy.sh cycler <cs_id>` -> deploy an instance of cycler node for cs_id cycler station

**Comment by javibu13** [comment]
Done (scpi_sniffer.service is not developed yet)
