### ISSUE TITLE
Merge shared objects while creating new attributes

### ISSUE THREAD

**Issue by RobertoAldea** [WattRex/Battery-Cycler-Controller#41]
**Describe the bug**
Cannot merge an object if new attributes has been created

**Expected behavior**
The ext meas should be able to add new attributes and merge them to the global variable

**Additional context**
The solution should be in controller but could also be in sys shared

**Comment by mariuscrsn** [comment]
Solved on [Sys shd merge](https://github.com/WattRex/System-Tools/pull/26)
